_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
colsample_bytree:
    value: 1
learning_rate:
    value: 0.05
max_depth:
    value: 9
model:
    value: XGBoost
n_estimators:
    value: 1000
split_note:
    value: 80/20 from 95% (5% OOT excluded)
subsample:
    value: 0.8
