method: bayes
metric:
  name: val_auc
  goal: maximize

parameters:
  n_estimators:
    values: [500, 800, 1000, 1500, 2000, 2500, 3000]
  learning_rate:
    values: [0.01, 0.03, 0.05, 0.1]
  max_depth:
    values: [3, 4, 5, 6, 7, 9]
  subsample:
    values: [0.8, 0.9, 1.0]
  colsample_bytree:
    values: [0.8, 0.9, 1.0]
  scale_pos_weight:
    values: [2.0, 2.5, 3.0, 3.5, 4.0]
  gamma:
    values: [0, 1, 3, 5]
  min_child_weight:
    values: [1, 3, 5, 7]


program: src/experiments/sweep_xgboost.py