wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.9
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744239809
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 14
      - 23
      - 37
      4: 3.11.11
      5: 0.19.9
      8:
      - 5
      13: darwin-arm64
colsample_bytree:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.1
max_depth:
  desc: null
  value: 9
n_estimators:
  desc: null
  value: 1000
subsample:
  desc: null
  value: 0.8
